name: push

on:
  workflow_dispatch:
  push:
    paths:
    - src/**
    - .github/**

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0' ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        include-prerelease: true
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       
    - name: build image
      if: github.ref_name != 'master'
      uses: docker/build-push-action@v6
      with:
       push: false
       tags: futugyousuzu/ddddemo_project:latest
       context: ./src
       file: ./src/WebApiHost/Dockerfile
       
    - name: Push to Docker Hub
      if: github.ref_name == 'master'
      uses: docker/build-push-action@v6
      with:
       push: true
       tags: futugyousuzu/ddddemo_project:latest
       context: ./src
       file: ./src/WebApiHost/Dockerfile
